Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,38 +1,85 @@
-name: Webgoat                                 # workflow name
+name: Django                                  # workflow name
 
 on:
-  push:                                       
+  push:
     branches:                                 # similar to "only" in GitLab
       - main
 
 jobs:
   build:
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-20.04                    # similar to "image" in GitLab
     steps:
-      - run: echo "This is a build step"
+      - uses: actions/checkout@v2
+
+      - name: Setup python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.6'
+
+      - run: |
+          pip3 install --upgrade virtualenv
+          virtualenv env
+          source env/bin/activate
+          pip install -r requirements.txt
+          python manage.py check
 
   test:
     runs-on: ubuntu-20.04
     needs: build
     steps:
-      - run: echo "This is a test step"
-  odc-backend:
+      - uses: actions/checkout@v2
+
+      - name: Setup python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.6'
+
+      - run: |
+          pip3 install --upgrade virtualenv
+          virtualenv env
+          source env/bin/activate
+          pip install -r requirements.txt
+          python manage.py test taskManager
+
+  oast-snyk:
     runs-on: ubuntu-20.04
-    name: depecheck_test
+    needs: test
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Depcheck
-        uses: dependency-check/Dependency-Check_Action@main
-        id: Depcheck
+      - uses: actions/checkout@master
+      - uses: snyk/actions/setup@master
+      - uses: actions/setup-go@v1
         with:
-          project: 'webgoat'
-          path: '.'
-          format: 'CSV'
+          go-version: "1.13"
 
-      - name: Upload Test results
-        uses: actions/upload-artifact@master
+      - uses: actions/setup-node@v2
         with:
-           name: Depcheck report
-           path: ${{github.workspace}}/reports
+          node-version: '10.x'
+
+      - name: Install Node modules
+        run: npm install
+
+      - name: Run Snyk
+        run: snyk test --json > snyk-results.json
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        continue-on-error: true             # allow the build to fail, similar to allow_failure: true
+
+      - uses: actions/upload-artifact@v2
+        with:
+          name: Snyk
+          path: snyk-results.json
+        if: always()        # what is this for?
+
+  integration:
+    runs-on: ubuntu-20.04
+    needs: oast-snyk
+    steps:
+      - run: echo "This is an integration step"
+      - run: exit 1
+        continue-on-error: true
+
+  prod:
+    runs-on: ubuntu-20.04
+    needs: integration
+    steps:
+      - run: echo "This is a deploy step."
